---
- hosts: all
  become: true

  tasks:

    - shell: "{{item}}"
      with_items:
        # set up the bridge
        - ip link set down dev bridge | sleep 0
        - brctl delbr bridge | sleep 0
        - brctl addbr bridge
        - ip link set bridge type bridge vlan_filtering 1

        # add interfaces to the bridge
        - brctl addif bridge swp1
        - brctl addif bridge swp2
        - brctl addif bridge swp3
        - brctl addif bridge swp4
        - brctl addif bridge swp5

        # bring up the interfaces
        - ip link set up dev swp1
        - ip link set up dev swp2
        - ip link set up dev swp3
        - ip link set up dev swp4
        - ip link set up dev swp5
        - ip link set up dev bridge
