---
- hosts: all
  become: true

  tasks:
    - name: Install packages
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - bash-completion
        - python3-pip

    - name: Install python
      command: pip3 install redis

    - shell: "{{item}}"
      with_items:
        - ip addr add 192.168.147.3/24 dev eth1 | sleep 0
        - ip link set up dev eth1
