---
- hosts: all
  become: true

  tasks:
    - name: Install packages
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - bash-completion
        - build-essential

    - name: Install hiredis
      command: make install
      args:
        chdir: /opt/hiredis
