---
- hosts: all
  become: true

  tasks:
    - name: Install packages
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - bash-completion
        - python3-pip

    - name: Install python
      command: pip3 install redis
